#!/bin/bash

echo "Setting up environment for MediaBrowser..."
source /etc/mediabrowser.conf

usermod -u $USER_ID nobody
usermod -g $GROUP_ID users
usermod -s /bin/bash nobody

chown -R nobody:users /opt/mediabrowser
chown -R nobody:users /config
